import { Component, OnInit, inject } from '@angular/core';
import { Users } from '../models/user.model';
import { NgbModal, NgbModalConfig, NgbModalRef } from '@ng-bootstrap/ng-bootstrap';
import { UsersFormComponent } from './users-form/users-form.component';
import { PaginationInstance } from 'ngx-pagination';
import { Status } from '../enums/status.enum';

@Component({
  selector: 'app-users',
  templateUrl: './users.component.html',
  styleUrls: ['./users.component.css']
})
export class UsersComponent implements OnInit {

  listaUsuarios: Users = [
    {
      nome: "Xan-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.ATIVO,
      dataCriacao: new Date(),
      ultimoAcesso: new Date(),
    },
    {
      nome: "Ran-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.PENDENTE,
      dataCriacao: new Date(),
      ultimoAcesso: null,
    },
    {
      nome: "Ran-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.BLOQUEADO,
      dataCriacao: new Date(),
      ultimoAcesso: new Date(),
    },
    {
      nome: "Xan-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.ATIVO,
      dataCriacao: new Date(),
      ultimoAcesso: new Date(),
    },
    {
      nome: "Ran-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.PENDENTE,
      dataCriacao: new Date(),
      ultimoAcesso: null,
    },
    {
      nome: "Ran-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.BLOQUEADO,
      dataCriacao: new Date(),
      ultimoAcesso: new Date(),
    },
    {
      nome: "Xan-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.ATIVO,
      dataCriacao: new Date(),
      ultimoAcesso: new Date(),
    },
    {
      nome: "Ran-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.PENDENTE,
      dataCriacao: new Date(),
      ultimoAcesso: null,
    },
    {
      nome: "Ran-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.BLOQUEADO,
      dataCriacao: new Date(),
      ultimoAcesso: new Date(),
    },
    {
      nome: "Xan-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.ATIVO,
      dataCriacao: new Date(),
      ultimoAcesso: new Date(),
    },
    {
      nome: "Ran-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.PENDENTE,
      dataCriacao: new Date(),
      ultimoAcesso: null,
    },
    {
      nome: "Ran-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.BLOQUEADO,
      dataCriacao: new Date(),
      ultimoAcesso: new Date(),
    },
    {
      nome: "Xan-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.ATIVO,
      dataCriacao: new Date(),
      ultimoAcesso: new Date(),
    },
    {
      nome: "Ran-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.PENDENTE,
      dataCriacao: new Date(),
      ultimoAcesso: null,
    },
    {
      nome: "Ran-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.BLOQUEADO,
      dataCriacao: new Date(),
      ultimoAcesso: new Date(),
    },
    {
      nome: "Xan-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.ATIVO,
      dataCriacao: new Date(),
      ultimoAcesso: new Date(),
    },
    {
      nome: "Ran-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.PENDENTE,
      dataCriacao: new Date(),
      ultimoAcesso: null,
    },
    {
      nome: "Ran-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.BLOQUEADO,
      dataCriacao: new Date(),
      ultimoAcesso: new Date(),
    },
    {
      nome: "Xan-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.ATIVO,
      dataCriacao: new Date(),
      ultimoAcesso: new Date(),
    },
    {
      nome: "Ran-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.PENDENTE,
      dataCriacao: new Date(),
      ultimoAcesso: null,
    },
    {
      nome: "Ran-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.BLOQUEADO,
      dataCriacao: new Date(),
      ultimoAcesso: new Date(),
    },
    {
      nome: "Xan-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.ATIVO,
      dataCriacao: new Date(),
      ultimoAcesso: new Date(),
    },
    {
      nome: "Ran-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.PENDENTE,
      dataCriacao: new Date(),
      ultimoAcesso: null,
    },
    {
      nome: "Ran-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.BLOQUEADO,
      dataCriacao: new Date(),
      ultimoAcesso: new Date(),
    },
    {
      nome: "Xan-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.ATIVO,
      dataCriacao: new Date(),
      ultimoAcesso: new Date(),
    },
    {
      nome: "Ran-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.PENDENTE,
      dataCriacao: new Date(),
      ultimoAcesso: null,
    },
    {
      nome: "Ran-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.BLOQUEADO,
      dataCriacao: new Date(),
      ultimoAcesso: new Date(),
    },
    {
      nome: "Xan-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.ATIVO,
      dataCriacao: new Date(),
      ultimoAcesso: new Date(),
    },
    {
      nome: "Ran-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.PENDENTE,
      dataCriacao: new Date(),
      ultimoAcesso: null,
    },
    {
      nome: "Ran-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.BLOQUEADO,
      dataCriacao: new Date(),
      ultimoAcesso: new Date(),
    },
    {
      nome: "Xan-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.ATIVO,
      dataCriacao: new Date(),
      ultimoAcesso: new Date(),
    },
    {
      nome: "Ran-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.PENDENTE,
      dataCriacao: new Date(),
      ultimoAcesso: null,
    },
    {
      nome: "Ran-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.BLOQUEADO,
      dataCriacao: new Date(),
      ultimoAcesso: new Date(),
    },
    {
      nome: "Xan-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.ATIVO,
      dataCriacao: new Date(),
      ultimoAcesso: new Date(),
    },
    {
      nome: "Ran-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.PENDENTE,
      dataCriacao: new Date(),
      ultimoAcesso: null,
    },
    {
      nome: "Ran-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.BLOQUEADO,
      dataCriacao: new Date(),
      ultimoAcesso: new Date(),
    },
    {
      nome: "Xan-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.ATIVO,
      dataCriacao: new Date(),
      ultimoAcesso: new Date(),
    },
    {
      nome: "Ran-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.PENDENTE,
      dataCriacao: new Date(),
      ultimoAcesso: null,
    },
    {
      nome: "Ran-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.BLOQUEADO,
      dataCriacao: new Date(),
      ultimoAcesso: new Date(),
    },
    {
      nome: "Xan-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.ATIVO,
      dataCriacao: new Date(),
      ultimoAcesso: new Date(),
    },
    {
      nome: "Ran-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.PENDENTE,
      dataCriacao: new Date(),
      ultimoAcesso: null,
    },
    {
      nome: "Ran-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.BLOQUEADO,
      dataCriacao: new Date(),
      ultimoAcesso: new Date(),
    },
    {
      nome: "Xan-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.ATIVO,
      dataCriacao: new Date(),
      ultimoAcesso: new Date(),
    },
    {
      nome: "Ran-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.PENDENTE,
      dataCriacao: new Date(),
      ultimoAcesso: null,
    },
    {
      nome: "Ran-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.BLOQUEADO,
      dataCriacao: new Date(),
      ultimoAcesso: new Date(),
    },
    {
      nome: "Xan-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.ATIVO,
      dataCriacao: new Date(),
      ultimoAcesso: new Date(),
    },
    {
      nome: "Ran-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.PENDENTE,
      dataCriacao: new Date(),
      ultimoAcesso: null,
    },
    {
      nome: "Ran-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.BLOQUEADO,
      dataCriacao: new Date(),
      ultimoAcesso: new Date(),
    },
    {
      nome: "Xan-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.ATIVO,
      dataCriacao: new Date(),
      ultimoAcesso: new Date(),
    },
    {
      nome: "Ran-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.PENDENTE,
      dataCriacao: new Date(),
      ultimoAcesso: null,
    },
    {
      nome: "Ran-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.BLOQUEADO,
      dataCriacao: new Date(),
      ultimoAcesso: new Date(),
    },
    {
      nome: "Xan-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.ATIVO,
      dataCriacao: new Date(),
      ultimoAcesso: new Date(),
    },
    {
      nome: "Ran-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.PENDENTE,
      dataCriacao: new Date(),
      ultimoAcesso: null,
    },
    {
      nome: "Ran-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.BLOQUEADO,
      dataCriacao: new Date(),
      ultimoAcesso: new Date(),
    },
    {
      nome: "Xan-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.ATIVO,
      dataCriacao: new Date(),
      ultimoAcesso: new Date(),
    },
    {
      nome: "Ran-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.PENDENTE,
      dataCriacao: new Date(),
      ultimoAcesso: null,
    },
    {
      nome: "Ran-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.BLOQUEADO,
      dataCriacao: new Date(),
      ultimoAcesso: new Date(),
    },
    {
      nome: "Xan-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.ATIVO,
      dataCriacao: new Date(),
      ultimoAcesso: new Date(),
    },
    {
      nome: "Ran-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.PENDENTE,
      dataCriacao: new Date(),
      ultimoAcesso: null,
    },
    {
      nome: "Ran-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.BLOQUEADO,
      dataCriacao: new Date(),
      ultimoAcesso: new Date(),
    },
    {
      nome: "Xan-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.ATIVO,
      dataCriacao: new Date(),
      ultimoAcesso: new Date(),
    },
    {
      nome: "Ran-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.PENDENTE,
      dataCriacao: new Date(),
      ultimoAcesso: null,
    },
    {
      nome: "Ran-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.BLOQUEADO,
      dataCriacao: new Date(),
      ultimoAcesso: new Date(),
    },
    {
      nome: "Xan-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.ATIVO,
      dataCriacao: new Date(),
      ultimoAcesso: new Date(),
    },
    {
      nome: "Ran-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.PENDENTE,
      dataCriacao: new Date(),
      ultimoAcesso: null,
    },
    {
      nome: "Ran-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.BLOQUEADO,
      dataCriacao: new Date(),
      ultimoAcesso: new Date(),
    },
    {
      nome: "Xan-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.ATIVO,
      dataCriacao: new Date(),
      ultimoAcesso: new Date(),
    },
    {
      nome: "Ran-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.PENDENTE,
      dataCriacao: new Date(),
      ultimoAcesso: null,
    },
    {
      nome: "Ran-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.BLOQUEADO,
      dataCriacao: new Date(),
      ultimoAcesso: new Date(),
    },
    {
      nome: "Xan-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.ATIVO,
      dataCriacao: new Date(),
      ultimoAcesso: new Date(),
    },
    {
      nome: "Ran-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.PENDENTE,
      dataCriacao: new Date(),
      ultimoAcesso: null,
    },
    {
      nome: "Ran-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.BLOQUEADO,
      dataCriacao: new Date(),
      ultimoAcesso: new Date(),
    },
    {
      nome: "Xan-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.ATIVO,
      dataCriacao: new Date(),
      ultimoAcesso: new Date(),
    },
    {
      nome: "Ran-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.PENDENTE,
      dataCriacao: new Date(),
      ultimoAcesso: null,
    },
    {
      nome: "Ran-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.BLOQUEADO,
      dataCriacao: new Date(),
      ultimoAcesso: new Date(),
    },
    {
      nome: "Xan-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.ATIVO,
      dataCriacao: new Date(),
      ultimoAcesso: new Date(),
    },
    {
      nome: "Ran-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.PENDENTE,
      dataCriacao: new Date(),
      ultimoAcesso: null,
    },
    {
      nome: "Ran-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.BLOQUEADO,
      dataCriacao: new Date(),
      ultimoAcesso: new Date(),
    },
    {
      nome: "Xan-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.ATIVO,
      dataCriacao: new Date(),
      ultimoAcesso: new Date(),
    },
    {
      nome: "Ran-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.PENDENTE,
      dataCriacao: new Date(),
      ultimoAcesso: null,
    },
    {
      nome: "Ran-na",
      sobrenome: "Ran-na",
      email: "aaa@aa.com",
      status: Status.BLOQUEADO,
      dataCriacao: new Date(),
      ultimoAcesso: new Date(),
    },
    
  ];

  itemsPerPage: number[] = [10, 20, 50];

  config: PaginationInstance = {
    itemsPerPage: 10,
    currentPage: 1
  };


	filter: string = '';
  private modalService = inject(NgbModal);

  constructor(config: NgbModalConfig) { 
    config.backdrop = 'static';
		config.keyboard = false;
  }

  ngOnInit() {

  }

  open(): NgbModalRef {
    return this.modalService.open(UsersFormComponent, { size: 'lg' });
  }
  
  getSeverity(status: string ): string {
    if (status === Status.ATIVO) { return "success"; } 
    else if (status === Status.PENDENTE) { return "warning"; }
    else { return "danger"; }
  }
  
}

